### ISSUE TITLE
ERR: Can only construct StringValue from strings

### ISSUE THREAD

**Issue by alemela** [maxlath/wikidata-edit#19]
I'm tring the following create: 
```
wdEdit.entity.create({
  labels: { it: 'Chiesa della Natività della Vergine'},
  claims: {
    P17: 'Q38', //paese
    P969: { value: 'Via Bourbon del Monte, 31 - Acquapendente', references: { P143: 'Q52897564' } }, //indirizzo
    P1435: 'Q26971668', //stato patrimonio
    P528: { value: '1467347382497', qualifiers: { P972: 'Q52896862', P2699 : 'http://dati.beniculturali.it/iccd/cf/resource/CulturalInstituteOrSite/1467347382497' } ,
                           references: { P143: 'Q52897564' } }
  }
})
```
But Wikidata returns me this error:
```
{ Error: post err
    at got.post.then.res (/home/alessio/Scrivania/node_modules/wikidata-edit/lib/request.js:74:19)
    at process._tickCallback (internal/process/next_tick.js:178:7)
  error: 
   { code: 'modification-failed',
     info: 'Data value corrupt: Can only construct StringValue from strings',
     messages: 
      [ { name: 'wikibase-validator-bad-value',
          parameters: [ 'Can only construct StringValue from strings' ],
          html: 
           { '*': 'Valore dei dati corrotto: Can only construct StringValue from strings' } } ],
     '*': 'See https://www.wikidata.org/w/api.php for API usage. Subscribe to the mediawiki-api-announce mailing list at &lt;https://lists.wikimedia.org/mailman/listinfo/mediawiki-api-announce&gt; for notice of API deprecations and breaking changes.' },
  servedby: 'mw1344' }
```

**Comment by maxlath** [comment]
could you set `config.verbose = true` and post here the result, especially `post request params` logs? (after obfuscating your credentials/session cookies ;))
