### ISSUE TITLE
Error when creating entity

### ISSUE THREAD

**Issue by ucl-borisw** [maxlath/wikidata-edit#28]
Hi i have an error when i create entity with `wdEdit.entity.create(entityData)` it's returning :
```
******* edit entity err *******
{ Error: post err: Bad value type wikibase-entityid, expected string
    at body (/home/usr/Projects/Javascript/wikidata-edit/node_modules/wikidata-edit/lib/request.js:115:17)
    at tryCatcher (/home/usr/Projects/Javascript/wikidata-edit/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/usr/Projects/Javascript/wikidata-edit/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/usr/Projects/Javascript/wikidata-edit/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/usr/Projects/Javascript/wikidata-edit/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/usr/Projects/Javascript/wikidata-edit/node_modules/bluebird/js/release/promise.js:694:18)
    at _drainQueueStep (/home/usr/Projects/Javascript/wikidata-edit/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/home/usr/Projects/Javascript/wikidata-edit/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/home/usr/Projects/Javascript/wikidata-edit/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/usr/Projects/Javascript/wikidata-edit/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
  body:
   { error:
      { code: 'modification-failed',
        info: 'Bad value type wikibase-entityid, expected string',
        messages:
         [ { name: 'wikibase-validator-bad-value-type',
             parameters: [ 'wikibase-entityid', 'string' ],
             html: { '*': 'Bad value type wikibase-entityid, expected string' } } ],
        '*':
         'See https://test.wikidata.org/w/api.php for API usage. Subscribe to the mediawiki-api-announce mailing list at &lt;https://lists.wikimedia.org/mailman/listinfo/mediawiki-api-announce&gt; for notice of API deprecations and breaking changes.' },
     servedby: 'mw1232' } }
----------------
```

Here the post request:
```
******* post request params *******
{ url:
   'https://test.wikidata.org/w/api.php?action=wbeditentity&format=json',
  oauth: undefined,
  headers:
   { Cookie:
      'testwikidatawikiSession=cjljvj9aqohvk4e1ghm3u04mdo7nbcc4; path=/; secure; httponly ; testwikidatawikiUserID=3398; expires=Thu, 28-Nov-2019 10:14:05 GMT; Max-Age=31536000; path=/; secure; httponly ; testwikidatawikiUserName=Waaub; expires=Thu, 28-Nov-2019 10:14:05 GMT; Max-Age=31536000; path=/; secure; httponly ; forceHTTPS=true; expires=Fri, 28-Dec-2018 10:14:05 GMT; Max-Age=2592000; path=/; httponly ; centralauth_User=Waaub; expires=Thu, 28-Nov-2019 10:14:05 GMT; Max-Age=31536000; path=/; secure; httponly ; centralauth_Token=523647b9804bf4be82cb58bd8d413376; expires=Thu, 28-Nov-2019 10:14:05 GMT; Max-Age=31536000; path=/; secure; httponly ; centralauth_Session=8b67ef10669b267879f5737bda5ded55; path=/; secure; httponly ; loginnotify_prevlogins=2018-ge6aoc-954w2q08wzv89psp1ds66mnj4jm79rn; expires=Mon, 27-May-2019 10:14:05 GMT; Max-Age=15552000; path=/; secure; httponly',
     'User-Agent':
      'wikidata-edit/2.7.1 (https://github.com/maxlath/wikidata-edit)',
     'Content-Type': 'application/x-www-form-urlencoded' },
  body:
   'new=item&data=%7B%22labels%22%3A%7B%22fr%22%3A%7B%22language%22%3A%22fr%22%2C%22value%22%3A%22UCL%20-%20BIMS%20%3A%20Biblioth%C3%A8que%20de%20Mons%22%7D%7D%2C%22aliases%22%3A%7B%7D%2C%22descriptions%22%3A%7B%22en%22%3A%7B%22language%22%3A%22en%22%2C%22value%22%3A%22The%20library%20offers%20documentary%20resources%2C%20services%20and%20tools%22%7D%2C%22nl%22%3A%7B%22language%22%3A%22nl%22%2C%22value%22%3A%22De%20bibliotheek%20biedt%20documentaire%20bronnen%2C%20diensten%20en%20hulpmiddelen%22%7D%2C%22fr%22%3A%7B%22language%22%3A%22fr%22%2C%22value%22%3A%22La%20biblioth%C3%A8que%20propose%20des%20ressources%20documentaires%2C%20services%20et%20outils%22%7D%7D%2C%22claims%22%3A%7B%22P485%22%3A%5B%7B%22rank%22%3A%22normal%22%2C%22type%22%3A%22statement%22%2C%22mainsnak%22%3A%7B%22datavalue%22%3A%7B%22type%22%3A%22wikibase-entityid%22%2C%22value%22%3A%7B%22entity-type%22%3A%22item%22%2C%22numeric-id%22%3A183967%7D%7D%2C%22property%22%3A%22P485%22%2C%22snaktype%22%3A%22value%22%7D%7D%5D%2C%22P31%22%3A%5B%7B%22rank%22%3A%22normal%22%2C%22type%22%3A%22statement%22%2C%22mainsnak%22%3A%7B%22datavalue%22%3A%7B%22type%22%3A%22wikibase-entityid%22%2C%22value%22%3A%7B%22entity-type%22%3A%22item%22%2C%22numeric-id%22%3A378134%7D%7D%2C%22property%22%3A%22P31%22%2C%22snaktype%22%3A%22value%22%7D%7D%5D%2C%22P17%22%3A%5B%7B%22rank%22%3A%22normal%22%2C%22type%22%3A%22statement%22%2C%22mainsnak%22%3A%7B%22datavalue%22%3A%7B%22type%22%3A%22wikibase-entityid%22%2C%22value%22%3A%7B%22entity-type%22%3A%22item%22%2C%22numeric-id%22%3A31%7D%7D%2C%22property%22%3A%22P17%22%2C%22snaktype%22%3A%22value%22%7D%7D%5D%2C%22P969%22%3A%5B%7B%22rank%22%3A%22normal%22%2C%22type%22%3A%22statement%22%2C%22mainsnak%22%3A%7B%22datavalue%22%3A%7B%22type%22%3A%22string%22%2C%22value%22%3A%22Chauss%C3%A9e%20de%20Binche%20Mons%22%7D%2C%22property%22%3A%22P969%22%2C%22snaktype%22%3A%22value%22%7D%7D%5D%2C%22P1329%22%3A%5B%7B%22rank%22%3A%22normal%22%2C%22type%22%3A%22statement%22%2C%22mainsnak%22%3A%7B%22datavalue%22%3A%7B%22type%22%3A%22string%22%2C%22value%22%3A%22%2B32%20(0)%2065%2032%2032%2057%22%7D%2C%22property%22%3A%22P1329%22%2C%22snaktype%22%3A%22value%22%7D%7D%5D%2C%22P131%22%3A%5B%7B%22rank%22%3A%22normal%22%2C%22type%22%3A%22statement%22%2C%22mainsnak%22%3A%7B%22datavalue%22%3A%7B%22type%22%3A%22wikibase-entityid%22%2C%22value%22%3A%7B%22entity-type%22%3A%22item%22%2C%22numeric-id%22%3A665868%7D%7D%2C%22property%22%3A%22P131%22%2C%22snaktype%22%3A%22value%22%7D%7D%5D%2C%22P626%22%3A%5B%7B%22rank%22%3A%22normal%22%2C%22type%22%3A%22statement%22%2C%22mainsnak%22%3A%7B%22datavalue%22%3A%7B%22type%22%3A%22globecoordinate%22%2C%22value%22%3A%7B%22latitude%22%3A50.4479584%2C%22longitude%22%3A3.9925498%2C%22precision%22%3A0.002777777777777778%7D%7D%2C%22property%22%3A%22P626%22%2C%22snaktype%22%3A%22value%22%7D%7D%5D%2C%22P856%22%3A%5B%7B%22rank%22%3A%22normal%22%2C%22type%22%3A%22statement%22%2C%22mainsnak%22%3A%7B%22datavalue%22%3A%7B%22type%22%3A%22string%22%2C%22value%22%3A%22https%3A%2F%2Fuclouvain.be%2Ffr%2Fbibliotheques%2Fbims%22%7D%2C%22property%22%3A%22P856%22%2C%22snaktype%22%3A%22value%22%7D%7D%5D%7D%2C%22sitelinks%22%3A%7B%22commonswiki%22%3A%7B%22site%22%3A%22commonswiki%22%2C%22title%22%3A%22Category%3AUniversit%C3%A9_catholique_de_Louvain%22%7D%7D%7D&assert=user&token=09ab944b9cff59fa54f5aa16cb8dc62f5bfe6a74%2B%5C&summary=%23wikidatajs%2Fedit' }

Thank you
```

**Comment by ucl-borisw** [comment]
i have missunderstood `wikibase-entityid`, i thought it was a problem to create entity ID but in fact it's the property or wikidata ID who wasn't exist because i was in test environement.
