### ISSUE TITLE
Can't login/edit with custom wikibase instance

### ISSUE THREAD

**Issue by alemela** [maxlath/wikidata-edit#3]
You cannot login into a wikibase cutom instance because login is made via wikidata-token dependence and there the login URL is hardwritten. See: https://github.com/maxlath/wikidata-token/blob/master/lib/login.js#L12

Maybe also the API append in https://github.com/maxlath/wikidata-edit/blob/master/lib/instance.js#L6 could be problematic because "/w/" path is not the mediawiki standard one.

**Comment by maxlath** [comment]
So which part of the endpoint URL should be customizable? The whole URL?

**Comment by alemela** [comment]
Only `https://www.wikidata.org/w/`I think should works.

**Comment by federicomorando** [comment]
In case that helps in debugging, the aforementioned changes in login.js and instance.js allow for a successful connection (Success on login) on a non-Wikidata Wikibase installation, but then one cannot successfully edit creating a new item:

```
******* wbeditentity err *******
{ Error: post err
    at got.post.then.res (/home/federico/node_modules/wikidata-edit/lib/request.js:70:19)
    at process._tickCallback (internal/process/next_tick.js:109:7)
  error: 
   { code: 'badtoken',
     info: 'Invalid token',
     '*': 'See http://www.linkedcoins.org/wikibase/api.php for API usage' } }
----------------
******* failed wbeditentity attempt *******
{ Error: post err
    at got.post.then.res (/home/federico/node_modules/wikidata-edit/lib/request.js:70:19)
    at process._tickCallback (internal/process/next_tick.js:109:7)
  error: 
   { code: 'badtoken',
     info: 'Invalid token',
     '*': 'See http://www.linkedcoins.org/wikibase/api.php for API usage' } }

```
I assume it's a problem with wikidata-edit, but I have to add that there might be issues on the wikibase side, since it's a newly installed instance... in case you want to test on [http://www.linkedcoins.org/wikibase/](http://www.linkedcoins.org/wikibase/) for debugging purposes, I can happily create an account (it's mostly an empty wikibase installation at the moment).
_BTW, thanks for creating wikidata-edit!_

**Comment by maxlath** [comment]
@federicomorando that problem might also come from wikidata-token, which uses the login way I could figure out, but [that is now deprecated](https://github.com/maxlath/wikidata-token/issues/5). You should see this warning by setting `verbose: true` in your wikidata-edit config object (which passes the verbose parameter to wikidata-token)

**Comment by federicomorando** [comment]
@maxlath thanks. verbose was actually true: here is the full output trying to do the following:
```
wdEdit.entity.create({
  labels: { en: 'a label' }
})
```
Output:

```
login res { warnings: { login: { '*': 'Main-account login via action=login is deprecated and may stop working without warning. To continue login with action=login, see [[Special:BotPasswords]]. To safely continue using main-account login, see action=clientlogin.' } },
  login: { result: 'Success', lguserid: 3, lgusername: 'Botolo' } }
******* post request url *******
'http://www.linkedcoins.org/wikibase/api.php?action=wbeditentity&format=json'
----------------
******* post request params *******
{ headers: 
   { Cookie: 'wikibase_session=bdk6d9kujeq5mudge9ig413hlc8rs4bh; path=/; HttpOnly ; wikibaseUserID=3; expires=Mon, 25-Sep-2017 09:41:39 GMT; Max-Age=15552000; path=/; HttpOnly ; wikibaseUserName=Botolo; expires=Mon, 25-Sep-2017 09:41:39 GMT; Max-Age=15552000; path=/; HttpOnly ; wikibaseToken=2a5e231f218bf0fe8b48a8d8429389f2; expires=Mon, 25-Sep-2017 09:41:39 GMT; Max-Age=15552000; path=/; HttpOnly',
     'User-Agent': 'linkedcoins/v0.0.1 (http://linkedcoins.org)',
     'Content-Type': 'application/x-www-form-urlencoded' },
  body: 'new=item&assert=user&data=%7B%22labels%22%3A%7B%22en%22%3A%7B%22language%22%3A%22en%22%2C%22value%22%3A%22a%20label%22%7D%7D%7D&token=%2B%5C' }
----------------
******* wbeditentity err *******
{ Error: post err
    at got.post.then.res (/home/federico/node_modules/wikidata-edit/lib/request.js:70:19)
    at process._tickCallback (internal/process/next_tick.js:109:7)
  error: 
   { code: 'badtoken',
     info: 'Invalid token',
     '*': 'See http://www.linkedcoins.org/wikibase/api.php for API usage' } }
----------------
******* failed wbeditentity attempt *******
{ Error: post err
    at got.post.then.res (/home/federico/node_modules/wikidata-edit/lib/request.js:70:19)
    at process._tickCallback (internal/process/next_tick.js:109:7)
  error: 
   { code: 'badtoken',
     info: 'Invalid token',
     '*': 'See http://www.linkedcoins.org/wikibase/api.php for API usage' } }
----------------
******* post request url *******
'http://www.linkedcoins.org/wikibase/api.php?action=wbeditentity&format=json'
----------------
******* post request params *******
{ headers: 
   { Cookie: 'wikibase_session=bdk6d9kujeq5mudge9ig413hlc8rs4bh; path=/; HttpOnly ; wikibaseUserID=3; expires=Mon, 25-Sep-2017 09:41:39 GMT; Max-Age=15552000; path=/; HttpOnly ; wikibaseUserName=Botolo; expires=Mon, 25-Sep-2017 09:41:39 GMT; Max-Age=15552000; path=/; HttpOnly ; wikibaseToken=2a5e231f218bf0fe8b48a8d8429389f2; expires=Mon, 25-Sep-2017 09:41:39 GMT; Max-Age=15552000; path=/; HttpOnly',
     'User-Agent': 'linkedcoins/v0.0.1 (http://linkedcoins.org)',
     'Content-Type': 'application/x-www-form-urlencoded' },
  body: 'new=item&assert=user&data=%7B%22labels%22%3A%7B%22en%22%3A%7B%22language%22%3A%22en%22%2C%22value%22%3A%22a%20label%22%7D%7D%7D&token=%2B%5C' }
----------------
******* wbeditentity err *******
{ Error: post err
    at got.post.then.res (/home/federico/node_modules/wikidata-edit/lib/request.js:70:19)
    at process._tickCallback (internal/process/next_tick.js:109:7)
  error: 
   { code: 'badtoken',
     info: 'Invalid token',
     '*': 'See http://www.linkedcoins.org/wikibase/api.php for API usage' } }
----------------
******* edit entity err *******
{ Error: post err
    at got.post.then.res (/home/federico/node_modules/wikidata-edit/lib/request.js:70:19)
    at process._tickCallback (internal/process/next_tick.js:109:7)
  error: 
   { code: 'badtoken',
     info: 'Invalid token',
     '*': 'See http://www.linkedcoins.org/wikibase/api.php for API usage' } }
----------------
(node:8604) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: post err
(node:8604) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**Comment by maxlath** [comment]
@alemela @federicomorando could you try with the version 1.2.4 I just published?

**Comment by maxlath** [comment]
I went for a [fully customizable endpoint](https://github.com/maxlath/wikidata-edit#config) to aim for future-proofness ;)
`config.wikibaseInstance = 'https://mywikibase.instance/w/api.php'`

**Comment by alemela** [comment]
On my instance it works! Great!

Many thanks for your fast bug fixing!

**Comment by federicomorando** [comment]
It works great!
Thanks a lot for the instantaneous support!!
